// <auto-generated />
using System;
using AzureWebApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureWebApp.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureWebApp.Repository.WeatherEntity", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            Date = new DateOnly(2024, 1, 1),
                            Id = 0,
                            Summary = "Cool",
                            TemperatureC = 15
                        },
                        new
                        {
                            Date = new DateOnly(2024, 1, 2),
                            Id = 0,
                            Summary = "Warm",
                            TemperatureC = 22
                        },
                        new
                        {
                            Date = new DateOnly(2024, 1, 3),
                            Id = 0,
                            Summary = "Freezing",
                            TemperatureC = -5
                        },
                        new
                        {
                            Date = new DateOnly(2024, 1, 4),
                            Id = 0,
                            Summary = "Hot",
                            TemperatureC = 30
                        },
                        new
                        {
                            Date = new DateOnly(2024, 1, 5),
                            Id = 0,
                            Summary = "Mild",
                            TemperatureC = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
